# Generated by Django 3.0.3 on 2020-02-08 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codice_cliente', models.IntegerField()),
                ('codice_fiscale', models.CharField(max_length=50)),
                ('ragione_sociale', models.TextField()),
                ('nome', models.CharField(max_length=50)),
                ('indirizzo', models.CharField(max_length=50)),
                ('cap', models.IntegerField()),
                ('comune', models.TextField()),
                ('provincia', models.TextField()),
                ('codice_stato', models.TextField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
